"use client";

import { useEffect, useState, type ComponentType } from "react";
import Image from "next/image";
import Link from "next/link";
import { Activity, ArrowLeft, ChevronDown, ChevronLeft, ChevronRight, Clock3, Menu, MoreVertical, Search, ShieldCheck, UserPlus, UserX, Users, X } from "lucide-react";
import { SharedSidebar } from "@/components/admin/shared-sidebar";

type Icon = ComponentType<{ size?: number; strokeWidth?: number }>;
type User = { id: string; name: string; email: string; imageUrl: string; createdAt: number; lastSignInAt: number | null; banned: boolean; locked: boolean; role: unknown; workspace?: string | null };
type UserStats = { activeUsers: number; activeSince: string; newUsers: number; suspendedUsers: number };
function Topbar({ open, query, setQuery }: { open: () => void; query: string; setQuery: (value: string) => void }) { return <header className="admin-topbar"><button className="mobile-menu" onClick={open} aria-label="Open navigation"><Menu size={20}/></button><Link className="back-link" href="/"><ArrowLeft size={17}/>Overview</Link><label className="global-search users-search"><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search users by name or email..."/><kbd>⌘K</kbd></label><div className="topbar-actions"><button className="notification" aria-label="Notifications"><Activity size={19}/><span>12</span></button><div className="admin-profile"><span>AR</span><div><b>Admin User</b><small>Super Admin</small></div><ChevronDown size={14}/></div></div></header>; }
function Metric({ icon: MetricIcon, label, value, tone, live = false }: { icon: Icon; label: string; value: string; tone: string; live?: boolean }) { return <article className="user-metric"><span className={`user-metric-icon ${tone}`}><MetricIcon size={20}/></span><div><span>{label}</span><strong>{value}</strong><small className={live ? "metric-live" : "metric-muted"}>{live ? "Live from Clerk" : "Not tracked yet"}</small></div></article>; }
function UserMetrics({ total }: { total: number }) { const [stats, setStats] = useState<UserStats>(); useEffect(() => { let current = true; fetch("/api/admin/users?page=0").then(response => response.ok ? response.json() : null).then(body => { if (current && body?.stats) setStats(body.stats); }).catch(() => undefined); return () => { current = false; }; }, []); return <section className="user-metrics"><Metric icon={Users} label="Total Users" value={String(total)} tone="blue" live/><Metric icon={ShieldCheck} label="Active Users" value={stats ? String(stats.activeUsers) : "—"} tone="green" live={Boolean(stats)}/><Metric icon={UserPlus} label="New Users (30d)" value={stats ? String(stats.newUsers) : "—"} tone="blue" live={Boolean(stats)}/><Metric icon={UserX} label="Suspended Users" value={stats ? String(stats.suspendedUsers) : "—"} tone="amber" live={Boolean(stats)}/><Metric icon={Clock3} label="Pending Deletions" value="—" tone="red"/></section>; }
function formatDate(value: number) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
function initials(name: string) { return name.split(" ").filter(Boolean).slice(0, 2).map(part => part[0]).join("").toUpperCase() || "U"; }
function Avatar({ user }: { user: User }) { return user.imageUrl ? <Image className="user-avatar" src={user.imageUrl} alt="" width={38} height={38}/> : <span className="user-avatar initials-avatar">{initials(user.name)}</span>; }
function UserDetail({ user, close }: { user: User; close: () => void }) { return <div className="user-detail-backdrop" onClick={close}><aside className="user-detail-drawer" onClick={event => event.stopPropagation()}><button className="drawer-close" onClick={close} aria-label="Close user details"><X size={18}/></button><div className="drawer-user"><Avatar user={user}/><div><h2>{user.name}</h2><p>{user.email}</p></div></div><dl><div><dt>Clerk user ID</dt><dd title={user.id}>{user.id}</dd></div><div><dt>Role</dt><dd>{String(user.role)}</dd></div><div><dt>Status</dt><dd>{user.banned ? "Suspended" : user.locked ? "Locked" : "Active"}</dd></div><div><dt>Joined</dt><dd>{formatDate(user.createdAt)}</dd></div></dl></aside></div>; }
function UserTable({ users, loading, query, view }: { users: User[]; loading: boolean; query: string; view: (user: User) => void }) { return <div className="users-table-wrap"><table className="users-table"><thead><tr><th>User</th><th>Workspace</th><th>Role</th><th>Status</th><th>Joined</th><th>Last Sign In</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><div className="user-primary"><Avatar user={user}/><div><strong>{user.name}</strong><span>{user.email}</span><small title={user.id}>ID: {user.id}</small></div></div></td><td><span className="workspace-badge unset">Not set</span></td><td><span className="role-badge">{String(user.role)}</span></td><td><span className={`user-status-badge ${user.banned || user.locked ? "suspended" : "active"}`}><i/>{user.banned ? "Suspended" : user.locked ? "Locked" : "Active"}</span></td><td>{formatDate(user.createdAt)}</td><td>{user.lastSignInAt ? <span className="signin-date"><b>{formatDate(user.lastSignInAt)}</b><small>{new Date(user.lastSignInAt).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })}</small></span> : <span className="never-signin">Never</span>}</td><td><div className="user-actions"><button onClick={() => view(user)}>View</button><button aria-label={`More actions for ${user.name}`}><MoreVertical size={16}/></button></div></td></tr>)}</tbody></table>{loading && <div className="users-table-state"><span className="loading-ring"/><strong>Loading users...</strong></div>}{!loading && !users.length && <div className="users-table-state"><Users size={27}/><strong>No users found</strong><p>{query ? "Try changing your search or filters." : "No users have registered yet."}</p></div>}</div>; }
export default function UsersPage() { const [users, setUsers] = useState<User[]>([]), [query, setQuery] = useState(""), [loading, setLoading] = useState(true), [error, setError] = useState(""), [page, setPage] = useState(0), [total, setTotal] = useState(0), [open, setOpen] = useState(false), [selected, setSelected] = useState<User | null>(null); useEffect(() => { fetch(`/api/admin/users?query=${encodeURIComponent(query)}&page=${page}`).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setUsers(body.users); setTotal(body.total); }).catch(reason => setError(reason instanceof Error ? reason.message : "Unable to load users")).finally(() => setLoading(false)); }, [query, page]); const start = users.length ? page * 50 + 1 : 0; const end = Math.min((page + 1) * 50, total); return <div className="admin-shell"><SharedSidebar open={open} close={() => setOpen(false)}/>{open && <button className="sidebar-backdrop" onClick={() => setOpen(false)} aria-label="Close navigation"/>}<main className="admin-main"><Topbar open={() => setOpen(true)} query={query} setQuery={value => { setPage(0); setQuery(value); }}/><div className="dashboard-content users-content"><div className="page-heading"><h1>Users</h1><p>Manage accounts and review user activity across the platform.</p></div><UserMetrics total={total}/><section className="panel users-panel"><div className="users-toolbar"><div className="users-count"><strong>{total} users</strong><span>{loading ? "Refreshing..." : "Live from Clerk"}</span></div><div className="user-filters"><label className="table-search"><Search size={16}/><input value={query} onChange={event => { setPage(0); setQuery(event.target.value); }} placeholder="Search by name, email or user ID..."/></label>{["Role", "Status", "Workspace"].map(filter => <button className="filter-button" key={filter}>{filter}<ChevronDown size={13}/></button>)}</div></div>{error ? <div className="users-table-state error-state"><ShieldCheck size={28}/><strong>Unable to load users</strong><p>{error}</p><button onClick={() => location.reload()}>Retry</button></div> : <UserTable users={users} loading={loading} query={query} view={setSelected}/>}<div className="users-footer"><span>Showing {start}–{end} of {total} users</span><div className="pagination"><button disabled={!page} onClick={() => setPage(page - 1)} aria-label="Previous page"><ChevronLeft size={16}/></button><button className="current-page">{page + 1}</button><button disabled={(page + 1) * 50 >= total} onClick={() => setPage(page + 1)} aria-label="Next page"><ChevronRight size={16}/></button><button className="page-size">50 / page <ChevronDown size={13}/></button></div></div></section></div></main>{selected && <UserDetail user={selected} close={() => setSelected(null)}/>}</div>; }
