"use client";
import { useState } from "react";
import { Activity, Bell, BookOpen, BriefcaseBusiness, Brain, ChevronDown, CircleDollarSign, Clock3, Database, Download, FileText, LayoutDashboard, LifeBuoy, Menu, MoreVertical, Search, Settings, ShieldCheck, Sparkles, Users, X, Zap } from "lucide-react";
import { auditEvents, processingJobs, recentDocuments } from "@/lib/admin-data";

const navigation = [
  { label:"", items:[["Overview",LayoutDashboard]] },
  { label:"MANAGE", items:[["Users",Users],["Documents",FileText],["Processing",Activity],["AI Analysis",Sparkles],["Risks & Obligations",ShieldCheck],["Templates",BookOpen],["Lawyers & Firms",BriefcaseBusiness]] },
  { label:"BUSINESS", items:[["Subscriptions & Billing",CircleDollarSign],["Credits & Usage",Zap]] },
  { label:"SUPPORT", items:[["Support Requests",LifeBuoy],["Reports & Exports",Download]] },
  { label:"SYSTEM", items:[["Audit Logs",FileText],["System Settings",Settings]] },
] as const;
const metrics = [
  ["Total Users","2,845","18.6%",Users,"blue"],["Active Users","1,928","15.3%",ShieldCheck,"green"],
  ["Documents Uploaded","12,486","24.8%",FileText,"blue"],["Documents Processed","10,258","21.4%",Activity,"purple"],
  ["AI Analyses Completed","8,934","27.2%",Brain,"purple"],["Storage Used","488.7 GB","12.7%",Database,"orange"],
] as const;

function PanelHeader({title,action="View all"}:{title:string;action?:string}) { return <div className="reference-panel-head"><h2>{title}</h2>{action&&<button>{action}</button>}</div> }
function Sidebar({open,close}:{open:boolean;close:()=>void}) { return <aside className={`sidebar ${open?"open":""}`}><div className="brand"><span className="brand-mark">✓</span><div><b>LegallyBinding.AI</b><small>Admin Panel</small></div><button className="close-nav" onClick={close}><X size={18}/></button></div><nav>{navigation.map(group=><div className="nav-group" key={group.label||"home"}>{group.label&&<small>{group.label}</small>}{group.items.map(([label,Icon])=><button className={label==="Overview"?"active":""} key={label}><Icon size={16}/>{label}</button>)}</div>)}</nav><SystemStatus/></aside> }
function SystemStatus() { return <div className="system-status"><span className="status-dot"/><div><b>System Status</b><small>Operational</small><em>All systems running normally</em><hr/><b>API Health <strong>99.9%</strong></b><svg viewBox="0 0 180 30"><path d="M0 24L13 20L25 23L38 11L51 20L65 19L78 7L91 17L104 12L117 22L130 14L143 15L157 6L170 18L180 8" fill="none" stroke="#23b26d" strokeWidth="2"/></svg></div></div> }
function MetricCards() { return <section className="reference-metrics">{metrics.map(([label,value,growth,Icon,tone])=><article key={label}><span className={`metric-icon ${tone}`}><Icon size={18}/></span><div><small>{label}</small><strong>{value}</strong><em>↑ {growth}</em><p>vs May 1 – May 31</p></div></article>)}</section> }
function UserGrowthChart() { return <section className="panel growth-panel"><PanelHeader title="User Growth" action="Last 30 days⌄"/><div className="chart-key"><span><i className="blue"/>Total Users</span><span><i className="green"/>New Users</span></div><div className="reference-chart"><span className="chart-y">4K<br/><br/>3K<br/><br/>2K<br/><br/>1K<br/><br/>0</span><svg viewBox="0 0 700 210" preserveAspectRatio="none"><path d="M0 170 C50 165 64 148 110 151 S180 129 225 133 S285 121 330 125 S395 112 438 116 S505 91 548 96 S625 74 700 78" fill="none" stroke="#176bff" strokeWidth="3"/><path d="M0 190 C55 179 75 185 120 178 S185 182 226 172 S285 177 330 169 S395 174 438 163 S505 169 550 158 S625 163 700 153" fill="none" stroke="#24b47e" strokeWidth="2"/></svg></div><div className="reference-axis"><span>May 31</span><span>Jun 7</span><span>Jun 14</span><span>Jun 21</span><span>Jun 30</span></div></section> }
function DocumentStatusChart() { const items=[["Uploaded","3,256 (26.1%)","blue"],["Queued","1,245 (10.0%)","indigo"],["Processing","1,082 (8.7%)","orange"],["Completed","6,512 (52.2%)","green"],["Failed","391 (3.0%)","red"]]; return <section className="panel status-reference"><PanelHeader title="Documents by Status" action="Last 30 days⌄"/><div className="status-content"><div className="reference-donut"><div><b>12,486</b><span>Total</span></div></div><div className="status-legend">{items.map(([name,value,tone])=><span key={name}><i className={tone}/>{name}<b>{value}</b></span>)}</div></div></section> }
function AIUsageCard() { return <section className="panel ai-usage"><PanelHeader title="AI Usage (Tokens)" action="Last 30 days⌄"/><div className="ai-body"><strong>48.2M</strong><small>Total Tokens</small><div className="token-grid"><div><b>31.4M</b><span>Input Tokens</span></div><div><b>16.8M</b><span>Output Tokens</span></div></div><div className="cost-box"><span>Cost (Estimated)</span><b>$1,284.52</b></div><div className="token-grid bottom"><div><span>AI Requests</span><b>42,619</b></div><div><span>Avg. Cost / 1K Tokens</span><b>$0.0267</b></div></div></div></section> }
function RecentDocumentsTable() { return <section className="panel documents-panel"><PanelHeader title="Recent Documents"/><div className="compact-table"><table><thead><tr><th>Document</th><th>Owner</th><th>Status</th><th>Uploaded</th><th>Risk Level</th><th/></tr></thead><tbody>{recentDocuments.map(doc=><tr key={doc.name}><td><span className="tiny-file"><FileText size={13}/></span>{doc.name}</td><td>{doc.owner}</td><td><span className={`doc-status ${doc.status.toLowerCase()}`}>{doc.status}</span></td><td>{doc.uploaded}</td><td><span className={`risk-badge ${doc.risk.toLowerCase()}`}>{doc.risk}</span></td><td><MoreVertical size={14}/></td></tr>)}</tbody></table></div></section> }
function ProcessingQueue() { return <section className="panel queue-panel"><PanelHeader title="Processing Queue"/><div className="queue-stats"><span><b>12</b>In Queue</span><span><b>8</b>Processing</span><span><b>3</b>Failed</span></div><h3>Currently Processing</h3>{processingJobs.map(job=><div className="processing-job" key={job.name}><span className="tiny-file"><FileText size={13}/></span><div><b>{job.name}</b><small>{job.owner}</small></div><i><em style={{width:`${job.progress}%`}}/></i><strong>{job.progress}%</strong></div>)}</section> }
function RiskSummary() { const rows=[["Payment Terms",312,"red"],["Liability",245,"orange"],["Termination",198,"amber"],["Confidentiality",176,"green"],["Indemnification",149,"blue"],["Other",168,"purple"]] as const; return <section className="panel risk-panel"><PanelHeader title="Risk Summary"/><div className="risk-totals"><span><b>1,248</b>Total Risks</span><span><b>312</b>High Risk</span><span><b>624</b>Medium Risk</span><span><b>249</b>Low Risk</span></div><h3>Top Risk Categories</h3>{rows.map(([label,value,tone])=><div className="risk-row" key={label}><span>{label}</span><i><em className={tone} style={{width:`${value/3.12}%`}}/></i><b>{value} ({(value/12.48).toFixed(1)}%)</b></div>)}</section> }
function AuditLogTable() { return <section className="panel audit-panel"><PanelHeader title="Recent Activity (Audit Log)"/><div className="compact-table"><table><thead><tr><th>Action</th><th>User</th><th>Target</th><th>Details</th><th>IP Address</th><th>Time</th></tr></thead><tbody>{auditEvents.map(event=><tr key={`${event.action}-${event.time}`}><td>{event.action}</td><td>{event.user}</td><td>{event.target}</td><td>{event.details}</td><td>{event.ip}</td><td>{event.time}</td></tr>)}</tbody></table></div></section> }

export default function AdminDashboard() { const [open,setOpen]=useState(false); return <div className="admin-shell"><Sidebar open={open} close={()=>setOpen(false)}/>{open&&<button className="backdrop" onClick={()=>setOpen(false)}/>}<main className="main"><header className="topbar"><button className="menu-btn" onClick={()=>setOpen(true)}><Menu size={21}/></button><div className="top-title"><h1>Overview</h1><p>Welcome back, Admin. Here’s what’s happening with your platform.</p></div><label className="search top-search"><Search size={16}/><input placeholder="Search users, documents, contracts, risks..."/><kbd>⌘K</kbd></label><button className="icon-btn"><Bell size={18}/><i/></button><div className="admin-user"><span className="avatar">AR</span><div><b>Admin User</b><small>Super Admin</small></div><ChevronDown size={15}/></div></header><div className="content"><div className="page-tools"><button className="range"><Clock3 size={15}/>May 31 – Jun 30, 2026<ChevronDown size={13}/></button><button className="export"><Download size={15}/>Export<ChevronDown size={13}/></button></div><MetricCards/><div className="analytics-grid"><UserGrowthChart/><DocumentStatusChart/><AIUsageCard/></div><div className="operations-grid"><RecentDocumentsTable/><ProcessingQueue/><RiskSummary/></div><AuditLogTable/></div></main></div> }
