"use client";

import { useCallback, useDeferredValue, useEffect, useState } from "react";
import { AlertTriangle, CalendarClock, CircleAlert, ListChecks, MoreVertical, ShieldCheck } from "lucide-react";
import { AdminSectionShell, DetailDrawer, DetailField, OwnerCell, SectionMetric, SectionPagination, TableState, formatAdminDate, type OwnerIdentity } from "@/components/admin/admin-section-shell";
import { fetchAdminJson } from "@/lib/admin-client";

type DocumentSummary = { filename: string; original_filename: string; status: string; classification: string | null };
type Finding = { id: string; kind: "risk" | "obligation"; document_id: string; title: string; severity?: "low" | "medium" | "high"; explanation: string; source_text: string | null; section_reference?: string | null; responsible_party?: string | null; due_date?: string | null; created_at: string; document: DocumentSummary | null; owner: OwnerIdentity };
type FindingsResponse = { items: Finding[]; stats: { risks: number; high: number; medium: number; low: number; obligations: number }; total: number; page: number; pageSize: number; kind: "risk" | "obligation" };
const emptyResponse: FindingsResponse = { items: [], stats: { risks: 0, high: 0, medium: 0, low: 0, obligations: 0 }, total: 0, page: 0, pageSize: 25, kind: "risk" };

export default function RisksObligationsPage() {
  const [query, setQuery] = useState("");
  const deferredQuery = useDeferredValue(query);
  const [kind, setKind] = useState<"risk" | "obligation">("risk");
  const [severity, setSeverity] = useState("all");
  const [page, setPage] = useState(0);
  const [data, setData] = useState<FindingsResponse>(emptyResponse);
  const [selected, setSelected] = useState<Finding | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");
  const requestData = useCallback(() => { const params = new URLSearchParams({ query: deferredQuery, kind, severity, page: String(page) }); return fetchAdminJson<FindingsResponse>(`/api/admin/risks-obligations?${params}`); }, [deferredQuery, kind, page, severity]);
  const applyData = useCallback((response: FindingsResponse) => { setData(response); setError(""); setLoading(false); }, []);
  useEffect(() => { let current = true; requestData().then(response => { if (current) applyData(response); }).catch(reason => { if (current) { setError(reason instanceof Error ? reason.message : "Unable to load findings"); setLoading(false); } }); return () => { current = false; }; }, [applyData, requestData]);
  const refresh = () => { setRefreshing(true); requestData().then(applyData).catch(reason => setError(reason instanceof Error ? reason.message : "Unable to load findings")).finally(() => setRefreshing(false)); };
  const switchKind = (next: "risk" | "obligation") => { setKind(next); setPage(0); setLoading(true); setSelected(null); };
  return <AdminSectionShell title="Risks & Obligations" description="Inspect legal findings and obligations extracted from documents across every workspace." query={query} setQuery={value => { setPage(0); setQuery(value); }} searchPlaceholder="Search findings, owners, parties, deadlines..." refreshing={refreshing} refresh={refresh}>
    <section className="section-metrics five-up"><SectionMetric icon={AlertTriangle} label="Total Risks" value={data.stats.risks} tone="purple" note="All severities"/><SectionMetric icon={CircleAlert} label="High Risk" value={data.stats.high} tone="red" note="Immediate review"/><SectionMetric icon={AlertTriangle} label="Medium Risk" value={data.stats.medium} tone="amber" note="Review recommended"/><SectionMetric icon={ShieldCheck} label="Low Risk" value={data.stats.low} tone="green" note="Lower priority"/><SectionMetric icon={CalendarClock} label="Obligations" value={data.stats.obligations} tone="blue" note="Extracted commitments"/></section>
    <section className="panel section-data-panel"><div className="section-toolbar findings-toolbar"><div className="section-tabs" role="tablist" aria-label="Finding type"><button className={kind === "risk" ? "active" : undefined} onClick={() => switchKind("risk")} role="tab" aria-selected={kind === "risk"}>Risk findings</button><button className={kind === "obligation" ? "active" : undefined} onClick={() => switchKind("obligation")} role="tab" aria-selected={kind === "obligation"}>Obligations</button></div><div className="toolbar-result-count"><strong>{data.total}</strong><span>{kind === "risk" ? "risk findings" : "obligations"}</span></div>{kind === "risk" && <label className="section-filter-label">Severity<select value={severity} onChange={event => { setPage(0); setLoading(true); setSeverity(event.target.value); }}><option value="all">All severities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label>}</div>
      <div className="section-table-wrap"><table className="section-table findings-table"><thead>{kind === "risk" ? <tr><th>Risk finding</th><th>Document</th><th>Owner</th><th>Severity</th><th>Section</th><th>Detected</th><th><span className="sr-only">Actions</span></th></tr> : <tr><th>Obligation</th><th>Document</th><th>Owner</th><th>Responsible party</th><th>Due date</th><th>Detected</th><th><span className="sr-only">Actions</span></th></tr>}</thead><tbody>{data.items.map(item => { const filename = item.document?.original_filename || item.document?.filename || item.document_id; return <tr key={item.id} onClick={() => setSelected(item)}><td><div className="section-primary-cell"><span className={`section-file-icon ${item.kind}`}><ListChecks size={16}/></span><div><strong title={item.title}>{item.title}</strong><span>{item.document?.classification || "Unclassified"}</span></div></div></td><td><span className="compact-document-name" title={filename}>{filename}</span></td><td><OwnerCell owner={item.owner}/></td>{kind === "risk" ? <><td><span className={`risk-badge ${item.severity}`}>{item.severity ? item.severity[0].toUpperCase() + item.severity.slice(1) : "Unknown"}</span></td><td>{item.section_reference || "—"}</td></> : <><td>{item.responsible_party || "Not specified"}</td><td><span className={item.due_date ? "due-date-value" : "muted-value"}>{item.due_date || "Not specified"}</span></td></>}<td>{formatAdminDate(item.created_at)}</td><td><button className="more-button" onClick={event => { event.stopPropagation(); setSelected(item); }} aria-label={`View ${item.title}`}><MoreVertical size={16}/></button></td></tr>; })}</tbody></table><TableState loading={loading} error={error} empty={!data.items.length} retry={refresh}/></div><SectionPagination page={page} pageSize={data.pageSize} total={data.total} setPage={next => { setLoading(true); setPage(next); }}/></section>
    {selected && <DetailDrawer title={selected.title} subtitle={selected.kind === "risk" ? `${selected.severity || "Unknown"} risk finding` : "Document obligation"} close={() => setSelected(null)}><dl className="section-detail-list"><DetailField label="Document">{selected.document?.original_filename || selected.document?.filename || selected.document_id}</DetailField><DetailField label="Owner"><OwnerCell owner={selected.owner}/></DetailField>{selected.kind === "risk" ? <><DetailField label="Severity"><span className={`risk-badge ${selected.severity}`}>{selected.severity || "Unknown"}</span></DetailField><DetailField label="Section">{selected.section_reference || "Not specified"}</DetailField></> : <><DetailField label="Responsible party">{selected.responsible_party || "Not specified"}</DetailField><DetailField label="Due date">{selected.due_date || "Not specified"}</DetailField></>}<DetailField label="Explanation"><p className="detail-copy">{selected.explanation}</p></DetailField><DetailField label="Detected">{formatAdminDate(selected.created_at)}</DetailField></dl>{selected.source_text && <div className="detail-quote"><strong>Source excerpt</strong><p>{selected.source_text}</p></div>}</DetailDrawer>}
  </AdminSectionShell>;
}
