"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowLeft, ChevronDown, ChevronLeft, ChevronRight, FileClock, FileImage, FileText, Filter, Menu, MoreVertical, RefreshCw, Search, ShieldCheck, TriangleAlert, Upload, X } from "lucide-react";
import { SharedSidebar } from "@/components/admin/shared-sidebar";

type DocumentRecord = { id: string; filename: string; original_filename: string; file_type: string; file_size: number; owner_clerk_id: string; status: string; classification: string | null; page_count: number | null; created_at: string; updated_at: string; error_message: string | null };

const formatFileSize = (bytes: number) => { if (!bytes) return "—"; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`; return `${(bytes / (1024 * 1024)).toFixed(1)} MB`; };
const titleCase = (value: string) => value ? value.charAt(0).toUpperCase() + value.slice(1).toLowerCase() : "—";
const fileName = (document: DocumentRecord) => document.original_filename || document.filename || "Untitled document";
const fileExtension = (document: DocumentRecord) => (document.file_type || fileName(document).split(".").pop() || "file").toLowerCase();
const dateParts = (value: string) => { const date = new Date(value); return { date: date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }), time: date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }) }; };

function FileTypeIcon({ document }: { document: DocumentRecord }) {
  const extension = fileExtension(document);
  const Icon = ["png", "jpg", "jpeg", "webp", "gif"].includes(extension) ? FileImage : FileText;
  return <span className={`document-file-icon ${extension}`}><Icon size={17}/></span>;
}

function StatusBadge({ status }: { status: string }) {
  const normalized = status.toLowerCase();
  return <span className={`document-status-badge ${normalized}`}><i/>{titleCase(status)}</span>;
}

function MetricCard({ label, value, icon: Icon, tone, supporting, live }: { label: string; value: string; icon: typeof FileText; tone: string; supporting: string; live?: boolean }) {
  return <article className="document-metric-card"><span className={`document-metric-icon ${tone}`}><Icon size={20}/></span><div><span>{label}</span><strong>{value}</strong><small className={live ? "metric-live" : "metric-muted"}>{supporting}</small></div></article>;
}

function DocumentMetrics({ documents, total }: { documents: DocumentRecord[]; total: number }) {
  const count = (status: string) => documents.filter(document => document.status.toLowerCase() === status).length;
  const percentage = (status: string) => total ? `${(count(status) / total * 100).toFixed(1)}% of total` : "No documents yet";
  return <section className="document-metrics"><MetricCard label="Total Documents" value={String(total)} icon={FileText} tone="blue" supporting="Live from Supabase" live/><MetricCard label="Completed" value={String(count("completed"))} icon={ShieldCheck} tone="green" supporting={percentage("completed")}/><MetricCard label="Processing" value={String(count("processing") + count("queued"))} icon={FileClock} tone="amber" supporting={percentage("processing")}/><MetricCard label="Failed" value={String(count("failed"))} icon={TriangleAlert} tone="red" supporting={percentage("failed")}/><MetricCard label="Uploaded" value={String(count("uploaded"))} icon={Upload} tone="purple" supporting={percentage("uploaded")}/></section>;
}

function DocumentFilters({ query, setQuery, status, setStatus, refresh }: { query: string; setQuery: (value: string) => void; status: string; setStatus: (value: string) => void; refresh: () => void }) {
  return <div className="document-filter-toolbar"><label className="document-table-search"><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by file name, owner or ID..."/></label><label className="document-filter-field"><span>Status</span><select value={status} onChange={event => setStatus(event.target.value)}><option value="all">All statuses</option><option value="uploaded">Uploaded</option><option value="queued">Queued</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="failed">Failed</option></select></label><label className="document-filter-field"><span>Type</span><select defaultValue="all"><option value="all">All types</option><option value="pdf">PDF</option><option value="docx">DOCX</option><option value="image">Images</option></select></label><label className="document-filter-field"><span>Classification</span><select defaultValue="all"><option value="all">All classifications</option></select></label><label className="document-filter-field"><span>Workspace</span><select defaultValue="all"><option value="all">All workspaces</option></select></label><button className="document-more-filter"><Filter size={15}/>More filters</button><button className="document-export" onClick={refresh}><RefreshCw size={15}/>Refresh</button></div>;
}

function DocumentsTable({ documents, loading, query, onSelect }: { documents: DocumentRecord[]; loading: boolean; query: string; onSelect: (document: DocumentRecord) => void }) {
  return <div className="document-table-scroll"><table className="document-table"><thead><tr><th>Document</th><th>Owner / Workspace</th><th>Type</th><th>Status</th><th>Classification</th><th>Uploaded</th><th>Size</th><th>Pages</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{documents.map(document => { const uploaded = dateParts(document.created_at); const extension = fileExtension(document).toUpperCase(); return <tr key={document.id}><td><div className="document-primary"><FileTypeIcon document={document}/><div><strong title={fileName(document)}>{fileName(document)}</strong><small title={document.id}>ID: {document.id}</small></div></div></td><td><div className="document-owner"><span title={document.owner_clerk_id}>{document.owner_clerk_id}</span><small>Personal</small></div></td><td><span className={`document-type-badge ${extension.toLowerCase()}`}>{extension}</span></td><td><StatusBadge status={document.status}/></td><td><span className="document-classification">{document.classification || "—"}</span></td><td><span className="document-uploaded"><b>{uploaded.date}</b><small>{uploaded.time}</small></span></td><td>{formatFileSize(document.file_size)}</td><td>{document.page_count || "—"}</td><td><div className="document-actions"><button onClick={() => onSelect(document)}>View</button><button aria-label={`More actions for ${fileName(document)}`}><MoreVertical size={16}/></button></div></td></tr>; })}</tbody></table>{loading && <div className="document-table-state"><span className="loading-ring"/><strong>Loading documents...</strong></div>}{!loading && !documents.length && <div className="document-table-state"><FileText size={28}/><strong>No documents found</strong><p>{query ? "No documents match your search." : "Documents uploaded by users will appear here."}</p></div>}</div>;
}

function DocumentDetail({ document, close }: { document: DocumentRecord; close: () => void }) {
  const uploaded = dateParts(document.created_at);
  return <div className="detail-backdrop" onClick={close}><aside className="document-detail" onClick={event => event.stopPropagation()}><button className="detail-close" onClick={close} aria-label="Close document details"><X size={18}/></button><span className="detail-file"><FileText size={25}/></span><h2>{fileName(document)}</h2><p className="detail-muted">Metadata and processing details</p><dl><dt>Document ID</dt><dd>{document.id}</dd><dt>Owner</dt><dd>{document.owner_clerk_id}</dd><dt>Status</dt><dd><StatusBadge status={document.status}/></dd><dt>Classification</dt><dd>{document.classification || "—"}</dd><dt>Uploaded</dt><dd>{uploaded.date} at {uploaded.time}</dd><dt>File size</dt><dd>{formatFileSize(document.file_size)}</dd><dt>Pages</dt><dd>{document.page_count || "—"}</dd></dl>{document.error_message && <p className="detail-error">{document.error_message}</p>}<p className="privacy-note">Document contents are not displayed in the admin metadata view.</p></aside></div>;
}

function DocumentsPageSkeleton() { return <div className="dashboard-content"><div className="heading-skeleton skeleton"/><div className="document-metrics">{Array.from({ length: 5 }, (_, index) => <div className="document-metric-card skeleton" key={index}/>)}</div><div className="panel skeleton document-skeleton-panel"/></div>; }

export default function DocumentsPage() {
  const [documents, setDocuments] = useState<DocumentRecord[]>([]), [query, setQuery] = useState(""), [status, setStatus] = useState("all"), [page, setPage] = useState(0), [total, setTotal] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState(""), [menu, setMenu] = useState(false), [selected, setSelected] = useState<DocumentRecord | null>(null);
  const load = () => { setLoading(true); setError(""); fetch(`/api/admin/documents?query=${encodeURIComponent(query)}&status=${status}&page=${page}`).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setDocuments(body.documents); setTotal(body.total); }).catch(reason => setError(reason instanceof Error ? reason.message : "Unable to load documents")).finally(() => setLoading(false)); };
  useEffect(() => { fetch(`/api/admin/documents?query=${encodeURIComponent(query)}&status=${status}&page=${page}`).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setDocuments(body.documents); setTotal(body.total); }).catch(reason => setError(reason instanceof Error ? reason.message : "Unable to load documents")).finally(() => setLoading(false)); }, [query, status, page]);
  const visibleDocuments = useMemo(() => documents, [documents]);
  const start = visibleDocuments.length ? page * 25 + 1 : 0;
  const end = Math.min((page + 1) * 25, total);
  return <div className="admin-shell"><SharedSidebar open={menu} close={() => setMenu(false)}/>{menu && <button className="sidebar-backdrop" onClick={() => setMenu(false)} aria-label="Close navigation"/>}<main className="admin-main"><header className="admin-topbar"><button className="mobile-menu" onClick={() => setMenu(true)} aria-label="Open navigation"><Menu size={20}/></button><Link className="back-link" href="/"><ArrowLeft size={17}/>Overview</Link><label className="global-search"><Search size={17}/><input placeholder="Search files or owners..."/><kbd>⌘K</kbd></label><button className="document-refresh-top" onClick={load}><RefreshCw size={15}/>Refresh</button><button className="notification" aria-label="Notifications"><Activity size={19}/></button><div className="admin-profile"><span>AR</span><div><b>Admin User</b><small>Super Admin</small></div><ChevronDown size={14}/></div></header>{loading && !documents.length && !error ? <DocumentsPageSkeleton/> : <div className="dashboard-content documents-content"><div className="page-heading"><h1>Documents</h1><p>Review metadata, processing state and errors across every workspace.</p></div><DocumentMetrics documents={visibleDocuments} total={total}/><section className="panel documents-data-panel"><DocumentFilters query={query} setQuery={value => { setLoading(true); setError(""); setPage(0); setQuery(value); }} status={status} setStatus={value => { setLoading(true); setError(""); setPage(0); setStatus(value); }} refresh={load}/>{error ? <div className="document-table-state error-state"><ShieldCheck size={28}/><strong>Unable to load documents</strong><p>{error}</p><button onClick={load}>Retry</button></div> : <DocumentsTable documents={visibleDocuments} loading={loading} query={query} onSelect={setSelected}/>}<div className="documents-pagination"><span>Showing {start}–{end} of {total} documents</span><div><button disabled={!page} onClick={() => { setLoading(true); setPage(page - 1); }} aria-label="Previous page"><ChevronLeft size={16}/></button><button className="current-page">{page + 1}</button><button disabled={(page + 1) * 25 >= total} onClick={() => { setLoading(true); setPage(page + 1); }} aria-label="Next page"><ChevronRight size={16}/></button><button className="page-size">25 / page <ChevronDown size={13}/></button></div></div></section></div>}{selected && <DocumentDetail document={selected} close={() => setSelected(null)}/>}</main></div>;
}
